version: '3.8'

services:
  apache-php:
    image: php:8.2-apache
    container_name: apache-php
    ports:
      - "8080:80"
    volumes:
      - ./html:/var/www/html
    depends_on:
    - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: exemple
      MYSQL_USER: usuari
      MYSQL_PASSWORD: contrasenya
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
